version: "3.9"

services:
  tests:
    container_name: firmness-tests
    build:
      context: .
      dockerfile: firmness.Tests/Dockerfile
    command: ["dotnet", "test", "--logger:trx"]
    networks:
      - firmness-net

  api:
    container_name: firmness-api
    build:
      context: .
      dockerfile: firmness.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      tests:
        condition: service_completed_successfully
      db:
        condition: service_started
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Host=db;Database=firmness;Username=postgres;Password=postgres"
    networks:
      - firmness-net

  front:
    container_name: firmness-front
    build:
      context: ./firmness.Client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      api:
        condition: service_started
    networks:
      - firmness-net

  db:
    container_name: firmness-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: firmness
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5444"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - firmness-net

networks:
  firmness-net:

volumes:
  pgdata: